# Generated by Django 4.2.5 on 2023-11-02 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('about', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('year_of_establishment', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kompaniya profili',
                'verbose_name_plural': 'Kompaniya profillari',
            },
        ),
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
    ]
