# Generated by Django 4.2.5 on 2023-10-10 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_collegemodel_schoolmodel_universitymodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
