# Generated by Django 4.2.5 on 2023-10-10 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_employeemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='collage',
        ),
        migrations.RemoveField(
            model_name='employeemodel',
            name='school',
        ),
        migrations.RemoveField(
            model_name='employeemodel',
            name='university',
        ),
    ]
