# Generated by Django 4.2.5 on 2023-10-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentModel',
        ),
    ]
