# Generated by Django 4.2.5 on 2023-10-10 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_remove_employeemodel_collage_and_more'),
        ('jobs', '0002_delete_commentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=10, verbose_name='phone')),
                ('comment', models.TextField(verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comments', to='users.employeemodel', verbose_name='blog')),
            ],
        ),
    ]
