# Generated by Django 4.2.5 on 2023-11-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_companymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companymodel',
            options={'ordering': ('-id',), 'verbose_name': 'Kompaniya', 'verbose_name_plural': 'Kompaniyalar'},
        ),
        migrations.AddField(
            model_name='companymodel',
            name='site',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
