# Generated by Django 4.2.5 on 2023-11-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_companymodel_options_companymodel_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='location',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
