# Generated by Django 4.2.5 on 2023-11-07 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_companymodel_location_companymodel_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companymodel',
            old_name='type',
            new_name='business_type',
        ),
    ]
