# Generated by Django 4.2.5 on 2023-11-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_rename_type_companymodel_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='hr_first_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companymodel',
            name='hr_last_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companymodel',
            name='hr_phone_number',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companymodel',
            name='hr_position',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companymodel',
            name='hr_telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='hr_third_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
