# Generated by Django 4.2.5 on 2023-10-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='your name')),
                ('email', models.EmailField(max_length=254, verbose_name='your email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone number')),
                ('subject', models.CharField(max_length=20, verbose_name='your subject')),
                ('message', models.TextField(blank=True, null=True, verbose_name='write message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время запроса')),
            ],
            options={
                'verbose_name': 'Связаться с нами',
                'verbose_name_plural': 'Связаться с нами',
            },
        ),
    ]
